
export interface NFT {
  id: string;
  name: string;
  description: string;
  imageUrl: string;
  owner: string;
  mintedAt: string;
  price: string;
}

export const mockNFTs: NFT[] = [
  {
    id: "NFT-1234",
    name: "Digital Dream",
    description: "A surreal landscape with floating islands and neon waterfalls",
    imageUrl: "https://images.unsplash.com/photo-1605810230434-7631ac76ec81?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
    owner: "0x71C7656EC7ab88b098defB751B7401B5f6d8976F",
    mintedAt: "2025-05-01",
    price: "0.15 ETH"
  },
  {
    id: "NFT-2345",
    name: "Future City",
    description: "A cyberpunk metropolis with flying cars and holographic advertisements",
    imageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
    owner: "0x71C7656EC7ab88b098defB751B7401B5f6d8976F",
    mintedAt: "2025-04-28",
    price: "0.2 ETH"
  },
  {
    id: "NFT-3456",
    name: "Space Explorer",
    description: "An astronaut floating through a colorful nebula",
    imageUrl: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
    owner: "0x8dC8CFc79B4Fd39FB9C16a3C6Bd4E7b35548026A",
    mintedAt: "2025-04-25",
    price: "0.18 ETH"
  },
  {
    id: "NFT-4567",
    name: "Digital Nature",
    description: "A fusion of natural elements and digital glitches",
    imageUrl: "https://images.unsplash.com/photo-1483058712412-4245e9b90334?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
    owner: "0x71C7656EC7ab88b098defB751B7401B5f6d8976F",
    mintedAt: "2025-05-03",
    price: "0.22 ETH"
  },
  {
    id: "NFT-5678",
    name: "Quantum Dreams",
    description: "Abstract visualization of quantum data patterns",
    imageUrl: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
    owner: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
    mintedAt: "2025-04-30",
    price: "0.25 ETH"
  },
  {
    id: "NFT-6789",
    name: "AI Portrait",
    description: "Portrait generated by artificial intelligence",
    imageUrl: "https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
    owner: "0x8dC8CFc79B4Fd39FB9C16a3C6Bd4E7b35548026A",
    mintedAt: "2025-05-02",
    price: "0.17 ETH"
  }
];
